[package]
name = "template-filling"
version = "0.1.0"
edition = "2021"
exclude = [
  ".vscode",
  ".gitignore",
  "template"
]

[dependencies]
chrono = "0.4.40"
clap = { version = "4.5.37", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
