[workspace]
members = [
  "template_filling",
  "template_filling_cli",
]
resolver = "2"
exclude = [
  ".vscode",
  ".gitignore",
  "template",
  "docs"
]

[workspace.dependencies]
chrono = "0.4.40"
clap = "4.5.41"
serde = "1.0.219"
serde_json = "1.0.140"
